### PR TITLE
Restructure repo to improve collaboration

### PR DESCRIPTION
**Pull request by openhab-5iver**
Everyone please review and test. I won't merge until there is some positive feedback. This PR has some major changes, which hopefully everyone will be supportive of. All documentation has also been updated to reflect these changes.

- The directories have been restructured, as detailed in #29, to allow for community contributions to be included in the repo.
- The `openhab` package has been renamed to `core`. This is a major breaking change, but it helps to distinguish between `community` contributions and `core` functionality.
- A `community` package and a directory for scripts has been added. This will store contributions from the community. The namespace will get tricky, so we'll need to be creative.
- Everything Esper has been moved to community.
- A `personal` package and a directory for scripts has been added. This is meant to hold your own personal modules and scripts.
- The `configuration.py` module at the root of `/automation/lib/jython/` is to be used for storing private or personal data. Community modules and scripts should include a `configuration.py.example` file to describe any variables that are expected to be in the file.
- The component scripts have been added back in, with proper naming to sort out the loading issues, and the ones dependent on Esper have been removed. Some of them add functionality that everyone can make use of, and some may never get used. I think they fit well in the core, since personal and community code can make use of them.
- I've included the `000_startup_delay.py` in the core scripts, as it seems everyone will need it until startup issues are corrected in ESH.
- Standardized the use of the `log` module and logger used across all modules and scripts.
- Corrected an issue with the `log` module, where WARN and TRACE weren't functioning.
- Reviewed modules and scripts, and did some cleanup, were possible.
- All of the documentation has been updated.

### CODE REVIEW

**Comment by mjcumming** [comment]
For code sharing.... wondering how to make it easier over a cut and paste method or more complex like using pip?

**Comment by smar000** [comment]
> 
> 
> For code sharing.... wondering how to make it easier over a cut and paste method or more complex like using pip?

In an ideal world, maybe something in PaperUI where users can see details on each available module, and then click to download/install as required?

**Comment by openhab-5iver** [comment]
OK, I've been testing this for a while now without issues, and just did another polishing of the docs. I think it's ready to merge! Please speak up now if you have any issues or concerns to be addressed.

**Comment by Andirs55** [comment]
working fine for me so far :)

**Pull request merged**
