### PR TITLE
class to make using item metadata easier

### PR DESCRIPTION
**Pull request by mjcumming**
Proposed class to make using item metadata easier. Class is designed to work with a single metadata namespace. Provides methods to read/write the Value for the namespace and the Configuration (key/value) pairs for the namespace.

Thoughts?

### CODE REVIEW

**Comment by smhgit** [comment]
@mjcumming 

Have you thought of adding namespace manipulation functions to the class, such as:

```
set_namespace - change item namespace context
namespaces - list of all item namespaces
delete_namespace - delete existing namespace
```

This also means that constructor can have only item name

**Comment by mjcumming** [comment]
Yes, was thinking about how to best approach that.

In my use case, I am always interacting with an single namespace of an item. It keeps the complexity of working with metadata lower. Having to set the namespace context could be problematic. The methods could be modified to always require a namespace.

The existing class does allow for deletion (remove) of the namespace.

I can’t think of any use case where one would want to enumerate all of the namespaces of an item?

**Comment by smhgit** [comment]
@mjcumming 

I agree that there is no immediate use for namespace functionality, so it can be postponed until real need.

Just to clarify, you don't need a name space in each function, the set_namespace function was for that purpose, to switch namespace, the functions should continue to work as they are.

**Comment by mjcumming** [comment]
@openhab-5iver, this is ready to merge unless there are any concerns.

**Comment by smhgit** [comment]
Any plans to merge it?

**Comment by openhab-5iver** [comment]
@mjcumming, are you OK with me closing this, as it looks like everything is in #88?

**Comment by mjcumming** [comment]
It's been too long for me to remember the difference between then. My occupy code is this so it works for it's purpose .

**Pull request closed without merging**
