### PR TITLE
Reworked items.add() to use builder style item creation

### PR DESCRIPTION
**Pull request by ScottKinSF**
I reworked lib/python/openhab/items.py to use a more generalized method for creating new objects, in particular the reworked items.add() method allows for creation of GroupItems with full support for group base item types and group functions.

### CODE REVIEW

**Comment by ScottKinSF** [comment]
Example usage of the enhanced functionality of items.add():

`"""
This example demonstrates item creation.
"""

import unittest
import time

from org.eclipse.smarthome.core.library.types.ArithmeticGroupFunction import And, Or
from org.slf4j import Logger, LoggerFactory

from openhab.testing import run_test
import openhab.items
reload(openhab.items)
import openhab.items


logger = LoggerFactory.getLogger("org.eclipse.smarthome.model.script.Rules")
    
class MyUnitTest(unittest.TestCase):
    def setUp(self):
        try:
            groupItems = {"gItem_0": Or(OnOffType.ON, OnOffType.OFF), "gItem_1": And(OnOffType.ON, OnOffType.OFF)}
            for iname, gfunc in groupItems.items():
                openhab.items.add(item = iname, item_type = "Group", gi_base_type = "Switch", group_function = gfunc)

            newItems = {"Item0": "Switch", "Item1": "Dimmer", "Item2": "Dimmer", "Item3": "Switch"}
            for iname, itype in newItems.items():
                openhab.items.add(iname, itype)

            gItem = ir.getItem("gItem_0")
            for member in ("Item0", "Item2"):
                gItem.addMember(ir.getItem(member))

            gItem = ir.getItem("gItem_1")
            for member in ("Item1", "Item3"):
                gItem.addMember(ir.getItem(member))
        except:
            import traceback
            logger.error(traceback.format_exc())

    def tearDown(self):
        itemNames = ("gItem_0", "gItem_1", "Item0", "Item1", "Item2", "Item3")
        for iname in itemNames:
            openhab.items.remove(iname)

    def test_item(self):
        itemNames = ("Item0", "Item1", "Item2", "Item3")
        for item in itemNames:
            events.postUpdate(item, "OFF")

        time.sleep(1)
        for item in itemNames:
            self.assertEqual(items[item].as(OnOffType), OnOffType.OFF)

        self.assertEqual(items["gItem_0"], OnOffType.OFF)
        self.assertEqual(items["gItem_1"], OnOffType.OFF)

        itemStates = {"Item0": "ON", "Item1": "33", "Item2": "67", "Item3": "OFF"}
        for item, cmd in itemStates.items():
            events.postUpdate(item, cmd)

        time.sleep(1)
        for item, state in itemStates.items():
            logger.info("item: {}".format(ir.getItem(item)))
            self.assertEqual(str(items[item]), state)

        self.assertEqual(items["gItem_0"], OnOffType.ON)
        self.assertEqual(items["gItem_1"], OnOffType.OFF)


run_test(MyUnitTest)
`

**Comment by openhab-5iver** [comment]
Nice! I'm going to be busy through this weekend with Halloweening, and would like to be able to test this before merging. It all looks good though, and bonus points for the unit test! We should add a new section into the repo for Testing... #29

**Comment by ScottKinSF** [comment]
I can't really claim authorship of the test script, I simply used _testing_example.py_ from the _Script Examples_ as its basis. I agree, the addition of a Testing section would a worthwhile addition to the openhab2-jython repository.

**Comment by openhab-5iver** [comment]
@mjcumming Thank you for reviewing! I still haven't had a chance to look at this, and I'm trying to get over the hump of a very nasty cold, so won't likely get to it for a while. I'll merge based on your review.

**Pull request merged**
