### PR TITLE
Documentation for date upgrades

### PR DESCRIPTION
**Pull request by CrazyIvan359**
Here we go, docs with clean commit history.

Rebasing would be the right way to do it, but I ended up having to delete my fork and make a new one because of my previous attempt to merge your upstream repo.

### CODE REVIEW

**Comment by openhab-5iver** [comment]
Sorry! I completely lost track of this one... been busy over in Java land. Thank you!

**Comment by CrazyIvan359** [comment]
No worries, I have been in the same boat doing other things while you worked to get the imports back.

I'd like to help more with development here and turning this library into an API. Let me know what I can do

**Comment by openhab-5iver** [comment]
Lots to help with... :smile: 

- The automation integration tests need to be fixed.
- The OH1 and Core actions need to be migrated to OH2/Thing actions/ScriptExtensions. This could be is a start to a scripting API.
- A decision has to be made on how ScriptEngines will be distributed. I'm about to post about this.
- An automation extension service needs to be setup for distributing rule templates.
- Automation documentation (UI and scripting) needs a major overhaul.
- The DSL .rules files need a new parser... I'm thinking one time migration to Jython.
- The OH-Jython-Scripter organization and the openhab2-jython repo need to be renamed, and repos setup for JS and Groovy. The existing JS libraries need to be migrated, using the same directory structure. And new libraries, similar to the Jython ones, need to be built.

I have another list somewhere...

**Comment by CrazyIvan359** [comment]
Well I have just started rewriting the current docs, though I wonder if such efforts should wait for this library to evolve into an API?

Do we have a better method of communicating than random threads on github

**Comment by openhab-5iver** [comment]
I'll get some team's setup, which might help with communication. You could open an issue to discuss the doc changes you are proposing. And you can get through to me by email (you'll find it in commit sign-offs). And there's always the forum. I plan to post details for everything above and more, and hopefully get some more devs involved to move the new rule engine forward.

**Comment by CrazyIvan359** [comment]
Sounds good. I will probably hold off on an issue for the docs for now as I really did just start it and don't have much to show.

You'll have to excuse my inexperience, this is my first time working on a project with more than just myself coding

**Comment by openhab-5iver** [comment]
Best to create an issue so that there is discussion _before_ any changes are made... prevents working in an area someone else is already working on and you get a feel for whether the changes you're proposing will be accepted.  The docs are due for an update... and a portion should be moved to the official docs.

**Comment by CrazyIvan359** [comment]
Good point. I'll write one up this weekend with my ideas so far.

I was thinking it might be time soon for it make an official appearance.

**Pull request merged**
